version: "2"

services:
  apacheds:
    container_name: "apacheds"
    image: 1000kit/apacheds
    ports:
       - "10389:10389"
    environment:
      - ADMIN_PASSWORD=secret
      - DOMAIN_NAME=1000kit
      - DOMAIN_SUFFIX=de
      
